# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lol.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(1126, 905))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 511, 831))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 371, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 60, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.check1 = QtWidgets.QPushButton(self.groupBox)
        self.check1.setEnabled(False)
        self.check1.setGeometry(QtCore.QRect(400, 60, 91, 31))
        self.check1.setObjectName("check1")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 150, 81, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.check2 = QtWidgets.QPushButton(self.groupBox)
        self.check2.setEnabled(False)
        self.check2.setGeometry(QtCore.QRect(400, 150, 91, 31))
        self.check2.setObjectName("check2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 220, 181, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.check3 = QtWidgets.QPushButton(self.groupBox)
        self.check3.setEnabled(False)
        self.check3.setGeometry(QtCore.QRect(400, 220, 91, 31))
        self.check3.setObjectName("check3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(10, 290, 181, 321))
        self.textEdit.setObjectName("textEdit")
        self.check4 = QtWidgets.QPushButton(self.groupBox)
        self.check4.setEnabled(False)
        self.check4.setGeometry(QtCore.QRect(400, 580, 91, 31))
        self.check4.setObjectName("check4")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 640, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 670, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 700, 181, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.print_y = QtWidgets.QPushButton(self.groupBox)
        self.print_y.setEnabled(False)
        self.print_y.setGeometry(QtCore.QRect(250, 740, 241, 31))
        self.print_y.setObjectName("print_y")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 740, 181, 81))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 150, 81, 31))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(580, 20, 511, 271))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser.setGeometry(QtCore.QRect(20, 40, 471, 211))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(580, 330, 511, 521))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar.setGeometry(QtCore.QRect(20, 80, 471, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 461, 41))
        self.label_2.setObjectName("label_2")
        self.start = QtWidgets.QPushButton(self.groupBox_3)
        self.start.setGeometry(QtCore.QRect(120, 140, 281, 41))
        self.start.setObjectName("start")
        self.earse = QtWidgets.QPushButton(self.groupBox_3)
        self.earse.setEnabled(False)
        self.earse.setGeometry(QtCore.QRect(120, 260, 281, 41))
        self.earse.setObjectName("earse")
        self.ESC = QtWidgets.QPushButton(self.groupBox_3)
        self.ESC.setGeometry(QtCore.QRect(120, 440, 281, 41))
        self.ESC.setObjectName("ESC")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(40, 340, 421, 51))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(120, 380, 281, 41))
        self.label_10.setObjectName("label_10")
        self.drow_graph = QtWidgets.QPushButton(self.groupBox_3)
        self.drow_graph.setEnabled(False)
        self.drow_graph.setGeometry(QtCore.QRect(120, 200, 281, 41))
        self.drow_graph.setObjectName("drow_graph")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_182 = QtWidgets.QAction(MainWindow)
        self.action_182.setObjectName("action_182")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_182)
        self.menu.addAction(self.action1)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.ESC.clicked.connect(MainWindow.close)
        self.earse.clicked.connect(self.textEdit.clear)
        self.earse.clicked.connect(self.lineEdit_3.clear)
        self.earse.clicked.connect(self.lineEdit_2.clear)
        self.earse.clicked.connect(self.lineEdit.clear)
        self.earse.clicked.connect(self.lineEdit_4.clear)
        self.earse.clicked.connect(self.textBrowser_2.clear)
        self.earse.clicked.connect(self.textBrowser.clear)
        self.earse.clicked.connect(self.lineEdit_5.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Введите количество пар (X, Y)"))
        self.check1.setText(_translate("MainWindow", "Check"))
        self.label_3.setText(_translate("MainWindow", "Введите интервал (x1, x2), на котором"))
        self.label_4.setText(_translate("MainWindow", "будет строиться график функции"))
        self.check2.setText(_translate("MainWindow", "Check"))
        self.label_5.setText(_translate("MainWindow", "Введите шаг между точками X"))
        self.check3.setText(_translate("MainWindow", "Check"))
        self.label_6.setText(_translate("MainWindow", "Введите все пары (X, Y) через пробел с новой строки"))
        self.check4.setText(_translate("MainWindow", "Check"))
        self.label_7.setText(_translate("MainWindow", "Можно получить значение в определенной точке X"))
        self.label_8.setText(_translate("MainWindow", "Введите значение X"))
        self.print_y.setText(_translate("MainWindow", "Получить значение F(x)"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Help"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Commands"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Заполненность входных данных</p></body></html>"))
        self.start.setText(_translate("MainWindow", "Старт"))
        self.earse.setText(_translate("MainWindow", "Стереть все данные"))
        self.ESC.setText(_translate("MainWindow", "Выход"))
        self.label_9.setText(_translate("MainWindow", "Программа аппроксимации таблично заданных"))
        self.label_10.setText(_translate("MainWindow", "функций многочленом Ньютона"))
        self.drow_graph.setText(_translate("MainWindow", "Нарисовать график функции"))
        self.menu.setTitle(_translate("MainWindow", "Создатель"))
        self.action.setText(_translate("MainWindow", "Соболев Сергей"))
        self.action_182.setText(_translate("MainWindow", "БИВ 182"))
        self.action1.setText(_translate("MainWindow", "1 курс"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

